// Generated by clj-native gen-handler-source. Do not edit.

import { makeHandler, byteLengthFingerprint } from 'ffi-wasm/handler-runtime';
import * as overrides from './proj-handler-overrides.mjs';

const busyMethods = ["context_create", "set_log_level", "ccall", "malloc", "heapf64_set", "heapf64_get", "read_string_array", "heapu8_set", "heapu8_get", "string_to_utf8", "utf8_to_string"];
const destroyMethods = ["context_destroy", "free"];

// C fnNames from the fndefs :destroy? flags. Nothing reads this.
const destroyFns = [];

const methods = {
  context_create: overrides.methods.context_create,
  set_log_level: overrides.methods.set_log_level,
  context_destroy: overrides.methods.context_destroy,
  ccall: overrides.methods.ccall,
  malloc: overrides.methods.malloc,
  free: overrides.methods.free,
  heapf64_set: overrides.methods.heapf64_set,
  heapf64_get: overrides.methods.heapf64_get,
  read_string_array: overrides.methods.read_string_array,
  heapu8_set: overrides.methods.heapu8_set,
  heapu8_get: overrides.methods.heapu8_get,
  string_to_utf8: overrides.methods.string_to_utf8,
  utf8_to_string: overrides.methods.utf8_to_string,
};

const fingerprint = byteLengthFingerprint(
  ["dbBytes", "iniBytes", "logLevel"],
  null,
);

export const create = makeHandler({
  init: overrides.init,
  methods,
  busyMethods,
  destroyMethods,
  fingerprint,
});

export default create;
export { destroyFns };

export const destroy = overrides.destroy;
