// Generated by clj-native gen-handler-source. Do not edit by hand;
// changes will be overwritten on the next bb gen-handler run.
//
// Wires a hand-written overrides module (init, methods, fingerprint)
// into clj-native's handler runtime, applying the busy/destroy
// classification computed from the consumer's fndefs.

import { makeHandler, byteLengthFingerprint } from 'ffi-wasm/handler-runtime';
import * as overrides from './proj-handler-overrides.mjs';

// Method classification. The handler runtime header says what it does.
const busyMethods = ["context_create", "set_log_level", "ccall", "malloc", "heapf64_set", "heapf64_get", "read_string_array", "heapu8_set", "heapu8_get", "string_to_utf8", "utf8_to_string"];
const destroyMethods = ["context_destroy", "free", "shutdown"];

// C fnNames from the fndefs :destroy? flags. Nothing reads this.
const destroyFns = ["proj_celestial_body_list_destroy", "proj_context_destroy", "proj_crs_info_list_destroy", "proj_destroy", "proj_get_crs_list_parameters_destroy", "proj_insert_object_session_destroy", "proj_int_list_destroy", "proj_list_destroy", "proj_operation_factory_context_destroy", "proj_string_destroy", "proj_string_list_destroy", "proj_unit_list_destroy"];

const methods = {
  context_create: overrides.methods.context_create,
  set_log_level: overrides.methods.set_log_level,
  context_destroy: overrides.methods.context_destroy,
  ccall: overrides.methods.ccall,
  malloc: overrides.methods.malloc,
  free: overrides.methods.free,
  heapf64_set: overrides.methods.heapf64_set,
  heapf64_get: overrides.methods.heapf64_get,
  read_string_array: overrides.methods.read_string_array,
  heapu8_set: overrides.methods.heapu8_set,
  heapu8_get: overrides.methods.heapu8_get,
  string_to_utf8: overrides.methods.string_to_utf8,
  utf8_to_string: overrides.methods.utf8_to_string,
  shutdown: overrides.methods.shutdown,
};

// Init-arg fields this handler is cached on. Bytes contribute their
// length, so a database costs one number rather than its contents.
const fingerprint = byteLengthFingerprint(
  ["dbBytes", "iniBytes", "logLevel"],
  null,
);

export const create = makeHandler({
  init: overrides.init,
  methods,
  busyMethods,
  destroyMethods,
  fingerprint: fingerprint,
});

export default create;
export { create as handler };
export { destroyFns };

// Module-level teardown for worker-router's coordinator shutdown, which
// invokes `mod.destroy` (see worker-bootstrap loadAllHandlers) once per
// worker when the pool terminates. Forwards to the overrides module's
// destroy when it exports one, else undefined (worker-router guards with
// `typeof mod.destroy === 'function'`). This is where a handler closes
// nested resources the emscripten Module holds open, such as the
// http-bridge fetch worker.
//
// A handler that exports no destroy is not a leak on node 26: terminate()
// reaps a nested worker_thread, measured with sixteen pool workers and
// requests in flight. Export one to close the resource on purpose.
export const destroy = overrides.destroy;
