// Generated by clj-native gen-handler-source. Do not edit.

import * as overrides from './proj-handler-overrides.mjs';

const busyMethods = ["context_create", "set_log_level", "ccall", "malloc", "heapf64_set", "heapf64_get", "read_string_array", "heapu8_set", "heapu8_get", "string_to_utf8", "utf8_to_string"];
const destroyMethods = ["context_destroy", "free"];

// C fnNames from the fndefs :destroy? flags. Nothing reads this.
const destroyFns = [];

const fingerprintFields = ["dbBytes", "iniBytes", "logLevel"];
const fingerprintPrefix = null;

// A module worker ignores the page importmap, so ffi-wasm loads from the URL
// that init-pool! puts in the init args. Outside a pool, Node resolves the
// bare specifier.
const loadFactory = async (initArgs) => {
  const ffi = await import(initArgs?.ffiWasmHandlerUrl ?? 'ffi-wasm/handler');
  const impl = overrides.methods(ffi);
  const methods = {
    context_create: impl.context_create,
    set_log_level: impl.set_log_level,
    context_destroy: impl.context_destroy,
    ccall: impl.ccall,
    malloc: impl.malloc,
    free: impl.free,
    heapf64_set: impl.heapf64_set,
    heapf64_get: impl.heapf64_get,
    read_string_array: impl.read_string_array,
    heapu8_set: impl.heapu8_set,
    heapu8_get: impl.heapu8_get,
    string_to_utf8: impl.string_to_utf8,
    utf8_to_string: impl.utf8_to_string,
  };
  return ffi.makeHandler({
    init: (args, ctx) => overrides.init?.(args, { ...ctx, ffi }),
    methods,
    busyMethods,
    destroyMethods,
    fingerprint: ffi.byteLengthFingerprint(fingerprintFields, fingerprintPrefix),
    label: null,
  });
};

let factory = null;

export const create = async (initArgs) => {
  // A failed import clears the memo, so a later create can retry.
  factory ??= loadFactory(initArgs).catch((e) => { factory = null; throw e; });
  return (await factory)(initArgs);
};

export default create;
export { destroyFns };

export const destroy = overrides.destroy;
